---
title: "Final Project RMD"
author: "Kashvi Ajitsaria"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)     
library(ggthemes)      
library(geofacet)     
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable
library(gganimate)
library(openintro)
library(plotly)
library(maptools)
library(rgeos)
theme_set(theme_minimal())
```

```{r}
india_coordinates <- readr::read_csv('https://raw.githubusercontent.com/ayushi98/DS-project/main/Indian%20Cities%20Database.csv') #For Indian Cities' Latitude and Longitude
india_pollution <- readr::read_csv('https://raw.githubusercontent.com/ayushi98/DS-project/main/city_day.csv') #For Indian Cities' Pollution Levels
india_factories <- readr::read_csv('https://raw.githubusercontent.com/nicolehiggins/Pollution_Project/main/india_factory_data.csv') #For Indian Factories Data
```

```{r}
india_city_pollution <-
  india_pollution %>% 
  left_join(india_coordinates,
            by = c("City")) 

india_factory_pollution <-
  india_city_pollution %>% 
  left_join(india_factories,
            by = c("State" = "State/Union Territory"))

india_city_pollution2 <-
  india_pollution %>% 
  left_join(india_coordinates,
            by = c("City")) %>% 
  pivot_longer(cols = c("PM2.5", "NO2", "CO", "SO2", "O3","AQI"),
               names_to = "Pollutant",
               values_to = "degree_pollution") %>% 
  drop_na(degree_pollution) %>% 
  mutate(month = month(Date, label = TRUE),
         year = year(Date)) 
```

INDIA MAP 1:

```{r}
ggmap(india)+
geom_point(data = india_city_pollution2 %>% filter(Pollutant == "AQI"),
           aes(x = Long, y = Lat, size = degree_pollution))+
theme(legend.background = element_blank(),
      legend.position = "bottomright")+
  theme_map()
```